// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserInsightSurvey.Context;

#nullable disable

namespace UserInsightSurvey.Migrations
{
    [DbContext(typeof(UserSurveyDbContext))]
    [Migration("20250525144206_UserAndAnswerSeedDataInit")]
    partial class UserAndAnswerSeedDataInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "LINQ",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 1,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 1,
                            QuestionId = 2,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 3,
                            QuestionId = 2,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 5,
                            QuestionId = 3,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Code First ile migration yönetimi deneyimim var.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 4,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 9,
                            QuestionId = 5,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 12,
                            QuestionId = 5,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 8,
                            Content = ".NET Core platform bağımsızdır.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 6,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 13,
                            QuestionId = 7,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 16,
                            QuestionId = 7,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 11,
                            Content = "JWT ile kimlik doğrulama kullanırım.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 8,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 17,
                            QuestionId = 9,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 23,
                            QuestionId = 10,
                            UserId = "252d1809-cd07-4ebd-87d1-83cefac3b78c"
                        },
                        new
                        {
                            Id = 101,
                            Content = "Delegates ve Events",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 1,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 1,
                            QuestionId = 2,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 3,
                            QuestionId = 2,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 104,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 5,
                            QuestionId = 3,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 105,
                            Content = "Migration ve Code First tecrübem var.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 4,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 106,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 9,
                            QuestionId = 5,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 107,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 12,
                            QuestionId = 5,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 108,
                            Content = ".NET Core platform bağımsızdır.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 6,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 109,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 13,
                            QuestionId = 7,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 16,
                            QuestionId = 7,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 111,
                            Content = "JWT ile kimlik doğrulama kullanırım.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 8,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 17,
                            QuestionId = 9,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 23,
                            QuestionId = 10,
                            UserId = "11111111-aaaa-bbbb-cccc-111111111111"
                        },
                        new
                        {
                            Id = 201,
                            Content = "LINQ ve Lambda Expressions",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 1,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 202,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 2,
                            QuestionId = 2,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 203,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 4,
                            QuestionId = 2,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 204,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 6,
                            QuestionId = 3,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 205,
                            Content = "Database First ile çalıştım.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 4,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 206,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 10,
                            QuestionId = 5,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 207,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 11,
                            QuestionId = 5,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 208,
                            Content = ".NET Core açık kaynaklıdır.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 6,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 209,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 14,
                            QuestionId = 7,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 210,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 15,
                            QuestionId = 7,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 211,
                            Content = "OAuth2 ile güvenlik sağlarım.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 8,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 212,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 18,
                            QuestionId = 9,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 213,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 24,
                            QuestionId = 10,
                            UserId = "22222222-aaaa-bbbb-cccc-222222222222"
                        },
                        new
                        {
                            Id = 301,
                            Content = "Async/Await kullanımı",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 1,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 302,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 1,
                            QuestionId = 2,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 303,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 2,
                            QuestionId = 2,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 304,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 7,
                            QuestionId = 3,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 305,
                            Content = "EF Core ile performans optimizasyonu yaptım.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 4,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 306,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 9,
                            QuestionId = 5,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 307,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 10,
                            QuestionId = 5,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 308,
                            Content = ".NET Core hızlıdır.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 6,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 309,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 13,
                            QuestionId = 7,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 310,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 15,
                            QuestionId = 7,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 311,
                            Content = "HTTPS zorunlu kullanırım.",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 8,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 312,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 19,
                            QuestionId = 9,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        },
                        new
                        {
                            Id = 313,
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OptionId = 25,
                            QuestionId = 10,
                            UserId = "33333333-aaaa-bbbb-cccc-333333333333"
                        });
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "ASP.NET Core",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 2,
                            Content = "WinForms",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "WPF",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "Blazor",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Visual Studio",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "Rider",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 7,
                            Content = "VS Code",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 8,
                            Content = "Diğer",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 9,
                            Content = "MVC",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 10,
                            Content = "MVVM",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 11,
                            Content = "Onion Architecture",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 12,
                            Content = "Clean Architecture",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 13,
                            Content = "SQL Server",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 14,
                            Content = "PostgreSQL",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 15,
                            Content = "MySQL",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 16,
                            Content = "MongoDB",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 17,
                            Content = "Azure",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 18,
                            Content = "AWS",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 19,
                            Content = "Google Cloud",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 20,
                            Content = "Hiçbiri",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 21,
                            Content = "Analiz",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 22,
                            Content = "Tasarım",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 23,
                            Content = "Kodlama",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 24,
                            Content = "Test",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 25,
                            Content = "Bakım",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            QuestionId = 10
                        });
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MultipleChoice")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "C# dilinde en çok kullandığınız özellik nedir?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = false,
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 2,
                            Content = ".NET teknolojilerinden hangileriyle çalıştınız?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = true,
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "En çok kullandığınız IDE hangisidir?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = true,
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Entity Framework ile ilgili deneyiminizi kısaca anlatır mısınız?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = false,
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 5,
                            Content = "Aşağıdaki mimari desenlerden hangilerini projelerinizde kullandınız?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = true,
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = ".NET Core ile .NET Framework arasındaki temel fark nedir?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = false,
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 7,
                            Content = "Hangi veritabanı sistemleriyle çalıştınız?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = true,
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Bir web API projesinde en önemli gördüğünüz güvenlik önlemi nedir?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = false,
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 9,
                            Content = "Aşağıdaki bulut servislerinden hangilerini kullandınız?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = true,
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 10,
                            Content = "Yazılım geliştirme sürecinde en çok hangi aşamada zorlanıyorsunuz?",
                            CreatedDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MultipleChoice = true,
                            QuestionType = 1
                        });
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "252d1809-cd07-4ebd-87d1-83cefac3b78c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b777b6f2-5ae3-4497-a2d9-f0ebb7caa004",
                            CvFilePath = "",
                            Email = "test@demo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Test",
                            NormalizedEmail = "TEST@DEMO.COM",
                            NormalizedUserName = "TEST@DEMO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9CXtfC6qm8bBQcnGEs/EqvfzgVf0H6Q1505j6h3ch0e9ERYlC9j6L/Nicemnukzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f90acaea-ce0c-4ce3-8954-02448fc11ddb",
                            Surname = "Kullanıcı",
                            TwoFactorEnabled = false,
                            UserName = "test@demo.com",
                            UserType = 1
                        },
                        new
                        {
                            Id = "11111111-aaaa-bbbb-cccc-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae81940d-2a14-478d-9eb7-bba88e302717",
                            CvFilePath = "",
                            Email = "ali.vural@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Ali",
                            NormalizedEmail = "ALI.VURAL@EXAMPLE.COM",
                            NormalizedUserName = "ALI.VURAL@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDcGDdS9WhsjKNmIvMJkv4LJ3p1jxU7mzSNiauH+71aUpk61+np8KZdwNZ1GO8blUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "80cf340d-3545-44a4-97d0-cf4e13b164f3",
                            Surname = "Vural",
                            TwoFactorEnabled = false,
                            UserName = "ali.vural@example.com",
                            UserType = 1
                        },
                        new
                        {
                            Id = "22222222-aaaa-bbbb-cccc-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aef3f959-d3bd-4442-9026-2c5fafa5c970",
                            CvFilePath = "",
                            Email = "zeynep.demir@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Zeynep",
                            NormalizedEmail = "ZEYNEP.DEMIR@EXAMPLE.COM",
                            NormalizedUserName = "ZEYNEP.DEMIR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJOsc3+rChRgKPHh4z+47rndtHk0EGpzP5REob+dXs3g2JMV3n89pdBKrh8MfnljIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6516d8c7-64f0-4e61-881e-76d5c32fcb63",
                            Surname = "Demir",
                            TwoFactorEnabled = false,
                            UserName = "zeynep.demir@example.com",
                            UserType = 1
                        },
                        new
                        {
                            Id = "33333333-aaaa-bbbb-cccc-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8f256dde-f468-442c-8b97-429643202094",
                            CvFilePath = "",
                            Email = "mehmet.kaya@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Mehmet",
                            NormalizedEmail = "MEHMET.KAYA@EXAMPLE.COM",
                            NormalizedUserName = "MEHMET.KAYA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIOzYXtPLGEwMW0seZlj0YoohAW7AmZHpZa56Ei+ULc5YRofX5n+LOM0YoNrkt3uCA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea53bf28-c409-4a5c-8053-8576d238176a",
                            Surname = "Kaya",
                            TwoFactorEnabled = false,
                            UserName = "mehmet.kaya@example.com",
                            UserType = 1
                        },
                        new
                        {
                            Id = "99999999-aaaa-bbbb-cccc-999999999999",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a74572d-aae7-48c7-991d-e81d6bb7638a",
                            CvFilePath = "",
                            Email = "admin@demo.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@DEMO.COM",
                            NormalizedUserName = "ADMIN@DEMO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMoJyJmozkFVHZEzU6G7tM8n/hZ2KUrL9W7ugKivMVKKPfS28LLZ9/NHmMJ6a4cL5Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da852466-6c9a-43c2-8782-226b0c15612f",
                            Surname = "Yönetici",
                            TwoFactorEnabled = false,
                            UserName = "admin@demo.com",
                            UserType = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UserInsightSurvey.Data.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UserInsightSurvey.Data.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInsightSurvey.Data.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UserInsightSurvey.Data.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.Answer", b =>
                {
                    b.HasOne("UserInsightSurvey.Data.Concrete.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId");

                    b.HasOne("UserInsightSurvey.Data.Concrete.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserInsightSurvey.Data.Concrete.User", "User")
                        .WithMany("Answers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.Option", b =>
                {
                    b.HasOne("UserInsightSurvey.Data.Concrete.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");
                });

            modelBuilder.Entity("UserInsightSurvey.Data.Concrete.User", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
